<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../managed/GameControls.cs" Link="GameControls.cs" />
    <Compile Include="../../managed/StartupHook.cs" Link="StartupHook.cs" />
    <Compile Include="../../managed/GameTouch.cs" Link="GameTouch.cs" />
    <Compile Include="../../managed/GameTouchAdapters.cs" Link="GameTouchAdapters.cs" />
  </ItemGroup>
</Project>
