use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::Context;
use serde::{Deserialize, Serialize};

use super::get_installed_mods_sync;

#[derive(Debug, Serialize, Deserialize)]
pub struct ModBlacklist {
    name: String,
    file: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ModBlacklistProfile {
    pub name: String,
    pub mods: Vec<ModBlacklist>,
    #[serde(default)]
    pub mod_options_order: Vec<String>,
}

fn validate_profile_name(profile_name: &str) -> anyhow::Result<()> {
    let invalid_windows_chars = ['<', '>', ':', '"', '|', '?', '*'];
    if profile_name.is_empty()
        || profile_name.len() > 128
        || profile_name == "."
        || profile_name == ".."
        || profile_name != profile_name.trim()
        || profile_name
            .chars()
            .any(|character| character.is_control() || character == '/' || character == '\\')
        || profile_name
            .chars()
            .any(|character| invalid_windows_chars.contains(&character))
    {
        anyhow::bail!("Invalid profile name");
    }
    Ok(())
}

fn profile_path(game_path: &str, profile_name: &str) -> anyhow::Result<PathBuf> {
    validate_profile_name(profile_name)?;
    Ok(Path::new(game_path)
        .join("celemod_blacklist_profiles")
        .join(format!("{profile_name}.json")))
}

pub fn apply_mod_blacklist_profile(
    game_path: &String,
    profile_name: &String,
    always_on_mod: &[String],
) -> anyhow::Result<()> {
    validate_profile_name(profile_name)?;
    let mut profile = get_mod_blacklist_profiles(game_path)
        .into_iter()
        .find(|v| &v.name == profile_name)
        .context("Profile not found")?;

    let blacklist = Path::new(game_path).join("Mods").join("blacklist.txt");

    let mods = get_installed_mods_sync(game_path.clone() + "/Mods");
    let mut profile_changed = false;
    for blacklisted_mod in &mut profile.mods {
        let Some(installed_mod) = mods.iter().find(|item| item.name == blacklisted_mod.name) else {
            continue;
        };
        if blacklisted_mod.file != installed_mod.file {
            blacklisted_mod.file = installed_mod.file.clone();
            profile_changed = true;
        }
    }

    if profile_changed {
        fs::write(
            profile_path(game_path, profile_name)?,
            serde_json::to_string_pretty(&profile)?,
        )?;
    }

    let always_on_files = mods
        .iter()
        .filter(|installed| always_on_mod.contains(&installed.name))
        .map(|installed| installed.file.as_str())
        .collect::<HashSet<_>>();
    let mut seen_files = HashSet::new();
    let blacklist_files = profile
        .mods
        .iter()
        .filter_map(|blacklisted| {
            let installed = mods.iter().find(|item| item.name == blacklisted.name)?;
            if always_on_files.contains(installed.file.as_str())
                || !seen_files.insert(installed.file.clone())
            {
                return None;
            }
            Some(installed.file.clone())
        })
        .collect::<Vec<_>>();

    fs::write(
        blacklist,
        format!(
            "# Profile: {}\n# This file is generated by CeleMod\n\n\n",
            profile_name
        ) + &blacklist_files.join("\n"),
    )?;

    write_mod_options_order(game_path, &profile.mod_options_order)?;

    Ok(())
}

/// Write modoptionsorder.txt from the given ordered file list.
fn write_mod_options_order(game_path: &String, order: &[String]) -> anyhow::Result<()> {
    let path = Path::new(game_path)
        .join("Mods")
        .join("modoptionsorder.txt");
    if order.is_empty() {
        // If no order specified, remove the file so Everest uses alphabetical order
        if path.exists() {
            fs::remove_file(&path)?;
        }
        return Ok(());
    }
    let content = format!(
        "# Mod Options order\n# This file is generated by CeleMod\n\n{}\n",
        order.join("\n")
    );
    fs::write(path, content)?;
    Ok(())
}

/// Update the mod_options_order in a profile and immediately apply it to modoptionsorder.txt.
pub fn set_mod_options_order(
    game_path: &String,
    profile_name: &String,
    order: Vec<String>,
) -> anyhow::Result<()> {
    let mut profile = get_mod_blacklist_profiles(game_path)
        .into_iter()
        .find(|v| &v.name == profile_name)
        .context("Profile not found")?;

    profile.mod_options_order = order;

    let profile_path = profile_path(game_path, profile_name)?;
    fs::write(
        &profile_path,
        serde_json::to_string_pretty(&profile).unwrap(),
    )?;

    write_mod_options_order(game_path, &profile.mod_options_order)?;

    Ok(())
}

pub fn get_current_profile(game_path: &String) -> anyhow::Result<String> {
    let blacklist = Path::new(game_path).join("Mods").join("blacklist.txt");
    let profiles = get_mod_blacklist_profiles(game_path);

    if blacklist.exists() {
        let data = fs::read_to_string(blacklist).unwrap();
        let profile_name = data
            .lines()
            .next()
            .map(|line| line.replace("# Profile: ", ""))
            .unwrap_or("Default".to_string());
        let current_profile = profiles.iter().find(|v| v.name == profile_name);

        if let Some(current_profile) = current_profile {
            Ok(current_profile.name.clone())
        } else {
            Ok("Default".to_string())
        }
    } else {
        Ok("Default".to_string())
    }
}

pub fn get_mod_blacklist_profiles(game_path: &String) -> Vec<ModBlacklistProfile> {
    let mut profiles = vec![];
    let blacklist_path = Path::new(game_path).join("celemod_blacklist_profiles");
    if blacklist_path.exists() {
        for entry in fs::read_dir(blacklist_path).unwrap() {
            let entry = entry.unwrap();
            let path = entry.path();
            if path.extension().unwrap() == "json" {
                let data = fs::read_to_string(path).unwrap();
                let profile: ModBlacklistProfile = serde_json::from_str(&data).unwrap();
                profiles.push(profile);
            }
        }
    } else {
        fs::create_dir_all(&blacklist_path).unwrap();
        // convert default blacklist to profile
        let default_blacklist = Path::new(&game_path).join("Mods").join("blacklist.txt");
        if default_blacklist.exists() {
            let data = fs::read_to_string(default_blacklist).unwrap();
            let mods = get_installed_mods_sync(game_path.clone() + "/Mods");
            let profile = ModBlacklistProfile {
                name: "Default".to_string(),
                mods: data
                    .lines()
                    .map(|v| v.trim())
                    .filter(|v| !v.starts_with('#'))
                    .map(|v| ModBlacklist {
                        name: {
                            if let Some(mod_name) = mods.iter().find(|m| m.file == v) {
                                mod_name.name.clone()
                            } else {
                                v.to_string()
                            }
                        },
                        file: v.to_string(),
                    })
                    .collect(),
                mod_options_order: vec![],
            };

            fs::write(
                blacklist_path.join("Default.json"),
                serde_json::to_string_pretty(&profile).unwrap(),
            )
            .unwrap();

            profiles.push(profile);
        }
    }

    // If no profiles exist, create a default empty profile
    if profiles.is_empty() {
        let profile = ModBlacklistProfile {
            name: "Default".to_string(),
            mods: vec![],
            mod_options_order: vec![],
        };
        let blacklist_path = Path::new(game_path).join("celemod_blacklist_profiles");
        fs::create_dir_all(&blacklist_path).unwrap();
        fs::write(
            blacklist_path.join("Default.json"),
            serde_json::to_string_pretty(&profile).unwrap(),
        )
        .unwrap();
        profiles.push(profile);
    }

    profiles
}

pub fn switch_mod_blacklist_profile(
    game_path: &String,
    profile_name: &String,
    mods: Vec<(&String, &String)>,
    enabled: bool,
) -> anyhow::Result<()> {
    validate_profile_name(profile_name)?;
    let profile = get_mod_blacklist_profiles(game_path)
        .into_iter()
        .find(|v| &v.name == profile_name)
        .context("Profile not found")?;

    // remove mod_name from profile or add it
    let mut new_profile = profile;

    if !enabled {
        for (mod_name, mod_file) in mods {
            if new_profile
                .mods
                .iter()
                .any(|v| &v.name == mod_name || &v.file == mod_file)
            {
                continue;
            }
            new_profile.mods.push(ModBlacklist {
                name: mod_name.clone(),
                file: mod_file.clone(),
            });
        }
    } else {
        new_profile.mods.retain(|v| {
            !mods
                .iter()
                .any(|(mod_name, mod_file)| &&v.name == mod_name || &&v.file == mod_file)
        });
    }

    let blacklist_path = profile_path(game_path, &new_profile.name)?;

    fs::write(
        blacklist_path,
        serde_json::to_string_pretty(&new_profile).unwrap(),
    )?;

    Ok(())
}

pub fn new_mod_blacklist_profile(game_path: &String, profile_name: &String) -> anyhow::Result<()> {
    let blacklist_path = profile_path(game_path, profile_name)?;

    fs::write(
        blacklist_path,
        serde_json::to_string_pretty(&ModBlacklistProfile {
            name: profile_name.clone(),
            mods: vec![],
            mod_options_order: vec![],
        })
        .unwrap(),
    )?;

    Ok(())
}

pub fn remove_mod_blacklist_profile(
    game_path: &String,
    profile_name: &String,
) -> anyhow::Result<()> {
    let blacklist_path = profile_path(game_path, profile_name)?;

    fs::remove_file(blacklist_path)?;

    Ok(())
}

pub fn get_current_blacklist_content(game_path: &String) -> anyhow::Result<String> {
    let blacklist = Path::new(game_path).join("Mods").join("blacklist.txt");
    if blacklist.exists() {
        Ok(fs::read_to_string(blacklist)?)
    } else {
        Ok("".to_string())
    }
}

pub fn import_blacklist_file_as_profile(
    game_path: &String,
    always_on_mod: &[String],
) -> anyhow::Result<String> {
    let blacklist = Path::new(game_path).join("Mods").join("blacklist.txt");
    if !blacklist.exists() {
        anyhow::bail!("blacklist.txt not found");
    }

    let data = fs::read_to_string(blacklist)?;
    let mods = get_installed_mods_sync(game_path.clone() + "/Mods");

    let profiles = get_mod_blacklist_profiles(game_path);
    let mut profile_name = "blacklist.txt".to_string();
    let mut suffix = 2;
    while profiles.iter().any(|profile| profile.name == profile_name) {
        profile_name = format!("blacklist.txt ({})", suffix);
        suffix += 1;
    }

    let profile = ModBlacklistProfile {
        name: profile_name.clone(),
        mods: data
            .lines()
            .map(|v| v.trim())
            .filter(|v| !v.starts_with('#') && !v.is_empty())
            .map(|v| ModBlacklist {
                name: {
                    if let Some(mod_name) = mods.iter().find(|m| m.file == v) {
                        mod_name.name.clone()
                    } else {
                        v.to_string()
                    }
                },
                file: v.to_string(),
            })
            .collect(),
        mod_options_order: vec![],
    };
    let blacklist_path = profile_path(game_path, &profile_name)?;
    fs::write(
        blacklist_path,
        serde_json::to_string_pretty(&profile).unwrap(),
    )?;

    // Make the imported profile current and rewrite the generated header. This also
    // applies the user's always-on list, so the sync prompt does not immediately
    // reappear for mods that CeleMod must keep enabled.
    apply_mod_blacklist_profile(game_path, &profile_name, always_on_mod)?;

    Ok(profile_name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn test_game_path(name: &str) -> String {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let path = std::env::temp_dir().join(format!(
            "celemod-blacklist-{name}-{}-{unique}",
            std::process::id()
        ));
        fs::create_dir_all(path.join("Mods")).unwrap();
        path.to_string_lossy().into_owned()
    }

    #[test]
    fn accepts_human_readable_profile_names() {
        assert!(validate_profile_name("Default").is_ok());
        assert!(validate_profile_name("周末联机 (2)").is_ok());
        assert!(validate_profile_name("blacklist.txt").is_ok());
    }

    #[test]
    fn rejects_profile_path_traversal_and_invalid_names() {
        for name in [
            "",
            ".",
            "..",
            "../outside",
            "folder/name",
            "folder\\name",
            " Cfg",
            "Cfg ",
        ] {
            assert!(validate_profile_name(name).is_err(), "accepted {name:?}");
        }
    }

    #[test]
    fn treats_multiple_metadata_names_in_one_archive_as_one_switchable_package() {
        let game_path = test_game_path("multi-metadata");
        let profile_name = "Default".to_string();
        get_mod_blacklist_profiles(&game_path);

        let main_name = "Bundle.Main".to_string();
        let extra_name = "Bundle.Extra".to_string();
        let file = "Bundle.zip".to_string();
        switch_mod_blacklist_profile(
            &game_path,
            &profile_name,
            vec![(&main_name, &file), (&extra_name, &file)],
            false,
        )
        .unwrap();

        let profile = get_mod_blacklist_profiles(&game_path)
            .into_iter()
            .find(|profile| profile.name == profile_name)
            .unwrap();
        assert_eq!(profile.mods.len(), 1);
        assert_eq!(profile.mods[0].file, file);

        switch_mod_blacklist_profile(&game_path, &profile_name, vec![(&extra_name, &file)], true)
            .unwrap();
        let profile = get_mod_blacklist_profiles(&game_path)
            .into_iter()
            .find(|profile| profile.name == profile_name)
            .unwrap();
        assert!(profile.mods.is_empty());

        fs::remove_dir_all(game_path).unwrap();
    }
}
